baseURL: https://dothidden.xyz/
languageCode: en-us
title: .hidden
buildDrafts: true
copyright: .hidden

params: 
  description: Adventures following the white rabbit
  mode: toggle
  social: 
    - name: GitHub
      icon: github
      url: https://github.com/orgs/dothidden/repositories
    - name: CTFtime
      icon: codesandbox
      url: https://ctftime.org/team/225182
    - name: RSS
      icon: rss
      url: https://dothidden.xyz/index.xml
  members:
    - name: sunbather
      link: icon1
      picture: https://avatars.githubusercontent.com/u/39965799?v=4
      tags: ['tag1','tag1','tag1','tag1']
      description:
        - line1
        - line2
    - name: zenbassi
      link: https://github.com/stefan-radu
      picture: https://avatars.githubusercontent.com/u/30214214?v=4
      tags: ['forensics','misc','pwn']
      description:
        - line1
        - thinks vim is cool
    - name: koyosu
      link: icon1
      picture: https://avatars.githubusercontent.com/u/39965799?v=4
      tags: ['tag1','tag1','tag1','tag1']
      description:
        - line1
        - line2
    - name: honeypot
      link: icon1
      picture: https://avatars.githubusercontent.com/u/39965799?v=4
      tags: ['tag1','tag1','tag1','tag1']
      description:
        - line1
        - line2
  excludedSections:
    - about
  homeWriteupCnt: 10

menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: Tags
      url: /tags
      weight: 2
    - name: About
      url: /about
      weight: 3
