baseURL: https://dothidden.xyz/
languageCode: en-us
title: .hidden
buildDrafts: true
copyright: .hidden

params:
  description: Adventures following the white rabbit
  mode: toggle
  social:
    - name: GitHub
      icon: github
      url: https://github.com/orgs/dothidden/repositories
    - name: CTFtime
      icon: codesandbox
      url: https://ctftime.org/team/225182
    - name: RSS
      icon: rss
      url: https://dothidden.xyz/index.xml
  members:
    - name: sunbather
      link: icon1
      picture: https://avatars.githubusercontent.com/u/39965799?v=4
      tags: [ 'rev','crypto','pwn' ]
      description:
        - bash wizard
        - video game enjoyer
    - name: zenbassi
      link: https://github.com/stefan-radu
      picture: https://avatars.githubusercontent.com/u/30214214?v=4
      tags: [ 'forensics','pwn' , 'rev']
      description:
        - likes vim a bit too much
        - into (film) photography
    - name: koyosu
      link: icon1
      picture: https://avatars.githubusercontent.com/u/39965799?v=4
      tags: [ 'tag1','tag1','tag1','tag1' ]
      description:
        - line1
        - line2
    - name: H0N3YP0T
      link: https://github.com/Mathis-Dory
      picture: https://ctftime.org/media/cache/52/af/52af19f614f045a44bcd409964613ac4.jpg
      tags: [ 'osint','forensics','web','misc' ]
      description:
        - I will find you, I'm really gonna find you...
        - The only Belgian on the team
        - FLAG{5TAY_CUR10U5_AND_CUNN1NG}
  excludedSections:
    - about
  homeWriteupCnt: 10

menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: Tags
      url: /tags
      weight: 2
    - name: About
      url: /about
      weight: 3
